-- defining the core functionalities of plugin
-- code generation
-- code explanation
-- code refactoring
-- test case generation
-- code commenter
-- code documenter
-- code debugger

-- features that are not required but would be nicer to implement
-- code completion
-- codebase analyser
