#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# startup applications
picom --config ~/.config/picom/picom.conf &
feh --randomize --bg-fill ~/.local/wallpapers/classic/ &
$HOME/.config/polybar/launch.sh &
