#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2'
bspc rule -a TelegramDesktop desktop='^3'
bspc rule -a Emacs desktop='^4'
bspc rule -a org.gnome.Nautilus desktop='^5'
bspc rule -a nekoray desktop='^8'

# startup applications
picom --config ~/.config/picom/picom.conf &
feh --randomize --bg-fill ~/.local/wallpapers/classic/ &
$HOME/.config/polybar/launch.sh &
