[colors.primary]
background = "0x000000"

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"
